basePath: /v1
consumes:
- application/json
definitions:
  models.Users:
    properties:
      created_at:
        description: When was the record created
        type: string
      first_name:
        description: User's first name
        type: string
      id:
        description: User's row ID
        type: integer
      last_name:
        description: User's last name
        type: string
      middle_name:
        description: User's middle name (if exists)
        type: string
      updated_at:
        description: When was the record last updated
        type: string
      username:
        description: User's username that is in use
        type: string
    type: object
  structs.HTTPError:
    properties:
      info:
        additionalProperties: {}
        description: Additional information to provide (if existd)
        type: object
      message:
        description: Reason for the error
        example: Something went wrong
        type: string
      status_code:
        description: HTTP Status Code
        example: 400
        maximum: 599
        minimum: 400
        type: integer
    required:
    - message
    - status_code
    type: object
  structs.User:
    properties:
      first_name:
        description: User's first name
        maxLength: 15
        minLength: 2
        type: string
      last_name:
        description: User's last name
        maxLength: 20
        minLength: 2
        type: string
      middle_name:
        description: User's middle name (if exists)
        maxLength: 15
        minLength: 0
        type: string
      username:
        description: User's username that is in use
        maxLength: 24
        minLength: 2
        type: string
    required:
    - first_name
    - last_name
    - username
    type: object
info:
  contact: {}
  description: The following project helps to learn echo and how to attach swagger
    to it.
  license:
    name: Mozilla Public License 2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/
  title: API to learn how to use swagger and echo
  version: "1.0"
paths:
  /users/add:
    put:
      consumes:
      - application/json
      description: Create a new user and returns it's record on success.
      parameters:
      - description: User object
        in: body
        name: user_details
        required: true
        schema:
          $ref: '#/definitions/structs.User'
      produces:
      - application/json
      responses:
        "200":
          description: User details as returned by the saved record
          schema:
            $ref: '#/definitions/models.Users'
        "400":
          description: Something in the request is wrong/unexpected
          schema:
            $ref: '#/definitions/structs.HTTPError'
        "500":
          description: Something in internal operation was bad
          schema:
            $ref: '#/definitions/structs.HTTPError'
      summary: Create a new user.
      tags:
      - Users
  /users/get/by_id/{id}:
    get:
      consumes:
      - application/json
      description: Finds a user by a given user id, and returning the record
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User details as returned by the saved record
          schema:
            $ref: '#/definitions/models.Users'
        "400":
          description: Something in the request is wrong/unexpected
          schema:
            $ref: '#/definitions/structs.HTTPError'
        "404":
          description: User was not found by provided ID
          schema:
            $ref: '#/definitions/structs.HTTPError'
        "500":
          description: Something in internal operation was bad
          schema:
            $ref: '#/definitions/structs.HTTPError'
      summary: Finds a user by a given user id, and returning the record
      tags:
      - Users
produces:
- application/json
schemes:
- http
swagger: "2.0"
